

const products = [
    {
        id:1,
        name: "Ingresso 27/9",
        desc: "vai ser foda",
        price: 27,
        image: "https://pbs.twimg.com/media/FqPvhb3WYAwUZun?format=jpg&name=medium",
        url: "https://www.punkykills.com/",
    },
    {
        id:2,
        name: "Ingresso 15/12",
        desc: "vai ser foda",
        price: 27,
        image: "https://pbs.twimg.com/media/FqPwuCgX0AA_D2q?format=jpg&name=medium",
        url: "https://www.punkykills.com/",
    },
    {
        id:3,
        name: "Copo",
        desc: "Copo ",
        price: 45.99,
        image: "https://static3.tcdn.com.br/img/img_prod/432031/copo_de_cerveja_termico_stanley_sem_tampa_adventure_matte_black_473ml_13148_2_20200416111118.jpg",
        url: "https://www.punkykills.com/",
    },
    {
        id:4,
        name: "camiseta preta",
        desc: "Camiseta Lacoste ",
        price: 80,
        image: "https://th.bing.com/th/id/OIP.0Fmp39Oi21Jy6QVKaliSUwHaHx?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:5,
        name: "chaveiro",
        desc: "Chaveiro ",
        price: 120,
        image: "https://lojavivara.vtexassets.com/arquivos/ids/210895/Chaveiro-Masculino-Couro-Preto-m1530043_set.jpg?v=637867858322500000",
        url: "https://www.punkykills.com/",
    },
    {
        id:6,
        name: "Camiseta preta2",
        desc: "Camiseta Lacoste",
        price: 80,
        image: "https://negociosfashion.com.br/wp-content/uploads/2017/06/805822.jpg",
        url: "https://www.punkykills.com/",
    },
    {
        id:7,
        name: "Moletom",
        desc: "Moletom hurley ",
        price: 120,
        image: "https://2.bp.blogspot.com/-qXBzSTVdhEc/V1tkn_K63lI/AAAAAAAAAvI/pQ5RWx24Qag2LGB2cauU-n6EyS3gtOG9gCLcB/s1600/20160609_163809.jpg",
        url: "https://www.punkykills.com/",
    },
    {
        id:8,
        name: "camiseta preta2",
        desc: "Camiseta Hollister",
        price: 80,
        image: "https://http2.mlstatic.com/kit-c30-camisetas-de-marcas-r-28000-cada-unidade-r-933-D_NQ_NP_859711-MLB20644135796_032016-F.jpg",
        url: "https://www.punkykills.com/",
    },
    {
        id:9,
        name: "boné",
        desc: "boné New Era",
        price: 80,
        image: "https://th.bing.com/th/id/OIP.C4vT_hJkp4NneSp35VSsQAHaHr?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:10,
        name: "Caneca",
        desc: "Caneca",
        price: 120,
        image: "https://th.bing.com/th/id/OIP.70iiOl8He1Z8DbPoTSwd9QHaHa?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:11,
        name: "pulseira",
        desc: "pulseira",
        price: 80,
        image: "https://th.bing.com/th/id/OIP.1q2hRANlZfaMINs2ljSx_QHaF-?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:12,
        name: "pulseira",
        desc: "pulseira",
        price: 80,
        image: "https://th.bing.com/th/id/OIP.1q2hRANlZfaMINs2ljSx_QHaF-?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:13,
        name: "Caneca",
        desc: "caneca",
        price: 120,
        image: "https://th.bing.com/th/id/OIP.70iiOl8He1Z8DbPoTSwd9QHaHa?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:14,
        name: "pulseira",
        desc: "pulseira",
        price: 80,
        image: "https://th.bing.com/th/id/OIP.1q2hRANlZfaMINs2ljSx_QHaF-?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    {
        id:15,
        name: "pulseira",
        desc: "pulseira",
        price: 80,
        image: "https://th.bing.com/th/id/OIP.1q2hRANlZfaMINs2ljSx_QHaF-?pid=ImgDet&rs=1",
        url: "https://www.punkykills.com/",
    },
    
];


module.exports = products;